## Задание на повторение материала

In [3]:
""" 1. 
Создать одномерный массив Numpy под названием a из 12
последовательных целых чисел чисел от 12 до 24 невключительно
"""

import numpy as np

a = np.arange(12, 24)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
""" 2.
Создать 5 двумерных массивов разной формы из массива a.
Не использовать в аргументах метода reshape число -1.
"""
a1 = a.reshape(1, 12)
a2 = a.reshape(2, 6)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(6, 2)

a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

In [5]:
""" 3.
Создать 5 двумерных массивов разной формы из массива a.
Использовать в аргументах метода reshape число -1
(в трех примерах - для обозначения числа столбцов, в двух - для строк).
"""

b1 = a.reshape(1, -1)
b2 = a.reshape(2, -1)
b3 = a.reshape(3, -1)
b4 = a.reshape(-1, 3)
b5 = a.reshape(-1, 2)

b1, b2, b3, b4, b5

(array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

In [21]:
""" 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
"""

# Ответ - нет, он не будет поддерживать операции, где ожидается одномерный массив,
# или будет делать не то, что ожидается
c = np.arange(1, 13).reshape(12, 1)
print(c, c.shape, c.ndim, sum(c))

d = c.flatten()
print(d, d.shape, d.ndim, sum(d))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] (12, 1) 2 [78]
[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) 1 78


In [24]:
""" 5.
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел
с плавающей запятой из нормального распределения со средним,
равным 0 и среднеквадратичным отклонением, равным 1.0.
Получить из этого массива одномерный массив с таким же атрибутом size,
как и исходный массив.
"""
norm = np.random.normal(size=(3,4))
norm1 = norm.flatten()
norm, norm1

(array([[ 0.12553693, -1.02024177,  0.33193263,  0.71749704],
        [-0.47479657, -0.56122968, -0.5630684 ,  1.09421739],
        [-1.367206  ,  1.03651292, -0.92396814, -0.19389219]]),
 array([ 0.12553693, -1.02024177,  0.33193263,  0.71749704, -0.47479657,
        -0.56122968, -0.5630684 ,  1.09421739, -1.367206  ,  1.03651292,
        -0.92396814, -0.19389219]))

In [26]:
""" 6.
Создать массив a, состоящий из целых чисел, убывающих
от 20 до 0 невключительно с интервалом 2."""
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [33]:
""" 7.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел,
убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?
"""

b = np.array([np.arange(20, 0, -2)])
b, "Разница между массивами a и b в свойствах ndim и shape"

(array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]]),
 'Разница между массивами a и b в свойствах ndim и shape')

In [37]:
""" 8.
Вертикально соединить массивы a и b. a - двумерный массив из нулей
число строк которого больше 1 и на 1 меньше, чем число строк двумерного
массива b, состоящего из единиц. Итоговый массив v должен иметь
атрибут size, равный 10.
"""
# (rows1+rows2)*columns == 10, rows2 == rows1 + 1 ==> rows1 = 2, rows2 = 3, columns = 2

a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v, v.size


(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

In [45]:
""" 9.
Создать одномерный массив а, состоящий из последовательности
целых чисел от 0 до 12. Поменять форму этого массива, чтобы
получилась матрица A (двумерный массив Numpy), состоящая из
4 строк и 3 столбцов. Получить матрицу At путем транспонирования
матрицы A. Получить матрицу B, умножив матрицу A на матрицу At
с помощью матричного умножения. Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?
"""

a = np.arange(0, 12)
A = a.reshape((4, 3))
At = A.T
At
B = A.dot(At)
np.linalg.det(B) # == 0.0
np.linalg.inv(B) # Error: singular matrix

LinAlgError: Singular matrix

In [49]:
""" 10.
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
"""
np.random.seed(42)


In [50]:
""" 11.
Создайте одномерный массив c, составленный из последовательности
16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
"""

c = np.random.randint(0, 16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [54]:
""" 12.
Поменяйте его форму так, чтобы получилась квадратная матрица C
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего
вопроса к матрице C, умноженной на 10. Вычислите определитель,
ранг и обратную матрицу D_inv для D.
"""

C = c.reshape((4, 4))
D = B + C*10
det = np.linalg.det(D)
rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
det, rank, D_inv

(-28511999.999999944,
 4,
 array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]]))

In [59]:
""" 13.
Приравняйте к нулю отрицательные числа в матрице D_inv,
а положительные - к единице. Убедитесь, что в матрице D_inv
остались только нули и единицы. С помощью функции numpy.where,
используя матрицу D_inv в качестве маски, а матрицы B и C -
в качестве источников данных, получите матрицу E размером 4x4.
Элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 1, должны быть равны соответствующему элементу
матрицы B, а элементы матрицы E, для которых соответствующий
элемент матрицы D_inv равен 0, должны быть равны соответствующему
элементу матрицы C.
"""

for i in range(D_inv.shape[0]):
    for j in range(D_inv.shape[1]):
        if D_inv[i][j] <= 0:
            D_inv[i][j] = 0
        else:
            D_inv[i][j] = 1

E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])